[[headers]]
for = "/*" # Aplica a todas las rutas
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "POST, GET, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"
